#!/usr/bin/env bash
# Bash script that transfers a file from a client to a server:
# Accepts 4 parameters:
# a. The path to the file to be transferred
# b. The IP of the server we want to transfer the file to
# c. The username scp connects with
# d. The path to the SSH private key that scp uses

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  file_path=$1
  server_ip=$2
  username=$3
  ssh_key=$4

  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~"
fi
