#!/usr/bin/env bash
# Installing web servers using nginx
# Requirements:
# 1. Install nginx on your web-01 server
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
#4. As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
#5. You can’t use systemctl for restarting nginx

# Install ngix
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Create a sample page
echo "Hello World!" > /etc/nginx/html/index.html

# Create server block files
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
}
" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx stop
sudo service nginx start
