#!/usr/bin/env bash
# Installation of web servers using nginx

# The requirements:
# 	1. Install nginx on web-01 server.
# 	2. Nginx should be listening on port 80.
# 	3. Returns a page containing "Hello World!"
#	   when queried at the root with a curl GET request.
# 	4. You can’t use systemctl for restarting nginx.

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow HTTP traffic in firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create sample page
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Test if nginx was successfully installed
sudo nginx -t

# Restart nginx to apply the changes
sudo service nginx restart
