#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World" when queried
#    at the root with a curl GET request.

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow HTTP traffic in firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create sample page
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Test if nginx was successfully installed
sudo nginx -t

# Restart nginx to apply the changes
sudo service nginx reload
