#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page.'

# Requirements:

#    The page must return an HTTP 404 error code
#    The page must contain the string Ceci n'est pas une page
#    Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

string_for_replacement="server_name _;\n\terror_page 404 \/404.html;\nlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
