#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02) servers'

# Requirements:
#	The name of the custom HTTP header must be "X-Served-By"
#	Value of the custom HTTP header must be the hostname of the Nginx server

# Update packages before installing nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html sample page
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Performing a "moved permanently redirection" (301)
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/@NathanielBasseyMain permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating 404 custom error page and redirect error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Testing configuration for syntax errors
sudo nginx -t

# Custom HTTP response header
sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx after implementing changes
sudo service nginx restart
