#!/usr/bin/env bash
# Install and configure HAProxy on the lb-01 server
# using the roundrobin algorithm

# update packages and install HAProxy
sudo apt-get update -y
sudo apt-get install haproxy -y

# configure HAProxy using the roundrobin algorithm
echo "
frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 278351-web-01 52.3.244.71:80 check
	server 278351-web-02 35.175.104.146:80 check
" >> /etc/haproxy/haproxy.cfg

# enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# restart HAProxy
sudo service haproxy restart
