#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes

printf "%-10s %-10s %-5s %-5s %-10s %-10s %-10s %-10s %-20s\n" \
    "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "COMMAND"


ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,comm --forest | \
    awk 'NR <= 50 { printf "%-10s %-10s %-5s %-5s %-10s %-10s %-10s %-10s %-20s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9 }'
