#!/usr/bin/env bash
# This script extends previous exercise command and displays line containing the bash word, thus allowing to easily get the PID of your bash process
# You cannot use pgrep
# Script must be shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
