#!/usr/bin/env bash
# Terminates the infinity and beyond program using the kill signal

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinite process
if [ -n "$id" ];
then
	kill -15 "$id"
fi
