#!/usr/bin/env bash
# Write a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

cd "$(dirname "$0")" || return

for item in *;
do
	if [ -e "$item" ];
	then
		name=$(echo "$item" | cut -d'-' -f2-)
		echo "$name"
	fi
done
