#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user

# Stop nginx if currently running
sudo service nginx stop

# Change default user from www-data to nginx in nginx.conf
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Change ownership of nginx directories to nginx user
chmod 644 /etc/nginx/nginx.conf

# Configure nginx so that all active IPs listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Apache may interfere with nginx so kill the process if it is running
pkill apache2

# Start nginx
sudo -u nginx service nginx start
