#!/usr/bin/env bash
# make bash script of previous task 7 lines long or less
sudo chmod 644 /etc/nginx/nginx.conf
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
